-- Ids become UUIDs (v7, generated by Prisma). There is no production data, so the tables are recreated.
DROP TABLE "signers";
DROP TABLE "sync_failures";
DROP TABLE "certificates";

-- CreateTable
CREATE TABLE "certificates" (
    "id" UUID NOT NULL,
    "shop" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "item" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "order_id" TEXT,
    "order_name" TEXT,
    "line_item_id" TEXT,
    "line_item_title" TEXT,
    "photo_url" TEXT,
    "photo_file_id" TEXT,
    "video_url" TEXT,
    "video_file_id" TEXT,
    "video_preview_url" TEXT,
    "photo_error" TEXT,
    "video_error" TEXT,
    "product_id" TEXT,
    "product_title" TEXT,
    "product_image_url" TEXT,
    "search_text" TEXT NOT NULL DEFAULT '',
    "latest_signed_on" DATE,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "certificates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "signers" (
    "id" UUID NOT NULL,
    "certificate_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "signed_on" DATE,
    "date_precision" "date_precision",
    "location" TEXT,

    CONSTRAINT "signers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sync_failures" (
    "certificate_id" UUID NOT NULL,
    "shop" TEXT NOT NULL,
    "action" "sync_action" NOT NULL,
    "version" INTEGER NOT NULL,
    "handle" TEXT NOT NULL,
    "stale_handles" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sync_failures_pkey" PRIMARY KEY ("certificate_id")
);

-- CreateIndex
CREATE INDEX "certificates_shop_created_at_id_idx" ON "certificates"("shop", "created_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "certificates_shop_updated_at_idx" ON "certificates"("shop", "updated_at" DESC);

-- CreateIndex
CREATE INDEX "certificates_shop_latest_signed_on_idx" ON "certificates"("shop", "latest_signed_on");

-- CreateIndex
CREATE INDEX "certificates_shop_order_id_idx" ON "certificates"("shop", "order_id");

-- CreateIndex
CREATE INDEX "certificates_shop_order_name_idx" ON "certificates"("shop", "order_name");

-- CreateIndex
CREATE INDEX "certificates_shop_line_item_id_idx" ON "certificates"("shop", "line_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "certificates_shop_code_key" ON "certificates"("shop", "code");

-- CreateIndex
CREATE INDEX "signers_certificate_id_position_idx" ON "signers"("certificate_id", "position");

-- CreateIndex
CREATE INDEX "sync_failures_shop_updated_at_idx" ON "sync_failures"("shop", "updated_at");

-- AddForeignKey
ALTER TABLE "signers" ADD CONSTRAINT "signers_certificate_id_fkey" FOREIGN KEY ("certificate_id") REFERENCES "certificates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CHECK constraints (from 20260926220319_checks)
ALTER TABLE certificates ADD CONSTRAINT certificates_code_canonical
  CHECK (code ~ '^[A-Z0-9]+(-[A-Z0-9]+)*$' AND length(code) BETWEEN 4 AND 32);
ALTER TABLE certificates ADD CONSTRAINT certificates_order_link_complete
  CHECK ((order_id IS NULL) = (line_item_id IS NULL)
     AND (order_id IS NULL) = (line_item_title IS NULL)
     AND (order_id IS NULL OR order_name IS NOT NULL));
ALTER TABLE signers ADD CONSTRAINT signers_date_precision_pair
  CHECK ((signed_on IS NULL) = (date_precision IS NULL)),
  ADD CONSTRAINT signers_month_is_first_day
  CHECK (date_precision IS DISTINCT FROM 'MONTH' OR EXTRACT(DAY FROM signed_on) = 1);
